### ISSUE TITLE
Using this library on Android

### ISSUE THREAD

**Issue by kal27** [fatsecret/fatsecret4j#2]
I am having some trouble integrating this library in android, although the library does not throw any exception, the FoodService(as well as other Service classes) always returns empty response.

**Comment by ranesr** [comment]
@kal27 This [commit](https://github.com/fatsecret/fatsecret4j/commit/87c37c32d13d8c05b3993ffd674f9cfbc0b06c31) takes care of using this library on android. Please check the [documentation](http://www.fatsecret4j.com/android).
