### ISSUE TITLE
Food are not showing when integrating with java using maven

### ISSUE THREAD

**Issue by deven6690** [fatsecret/fatsecret4j#4]
Hello,
I am integrating FatSecret Java API in my project using maven dependency. But when I hit the getFood API so frequently it is not showing any food(It is showing only for the first time), while foods are available as I have checked with the fat secret website.
So please tell me what is the issue and how to resolve it?

Thanks

**Comment by ranesr** [comment]
@deven6690 You might be using the BASIC edition from [FatSecret Platform API Editions](http://platform.fatsecret.com/api/Default.aspx?screen=prem) which has a limit of 5000 API calls/day. You need to contact fatsecret for getting access to either PREMIER Free or PREMIER edition.

I checked the getFood API using my API Keys, the results were available when I used the API.

Let me know if this helps.

**Comment by ranesr** [comment]
Closing this as I haven't heard back anything.
